### ISSUE TITLE
Currently doesn't work for production build

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/webui#603] opened 2017-11-03 04:23 UTC
Trying to use the newest code from webui (ea3664bde32490c3f082696726e4f334adc27901) together with go-ipfs. 

After installing the dependencies, I run `yarn build`, then add the hash to IPFS (`ipfs add -r dist/`) and replace the following line in go-ipfs with the root hash of the add: https://github.com/ipfs/go-ipfs/blob/0efdcadafb526ce0edce0a6ae4ca994740c7f844/core/corehttp/webui.go#L4 (then rebuild and start the newly built daemon)

After doing this, it quite doesn't work... First issue I hit was that there is a typo in the production configuration. See https://github.com/ipfs/webui/blob/ea3664bde32490c3f082696726e4f334adc27901/src/app/js/store/configure-store.prod.js#L3 Supposed to be `Middleware` instead of `Middlware`, notice the missing `e`.

After fixing that, things actually load but the CSS is not part of the HTML file that is loaded. See QmefLwZaGVCwRkdDMBNExWs5ahFERnyxDV7Ngnx9sgiefU

This is how the `index.html` ends up looking:

```
<!doctype html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/></head><body><div id="root"></div><script src="ipfs-webui.0.3.0.js"></script></body>
```

Started to dig into how `hjs-webpack` works and actually injects styles but gave up at this point.

**Comment by VictorBjelkholm** [comment] 2017-11-03 04:25
Ping @diasdavid and @alanshaw who I think were the last people who worked on this.

**Comment by dryajov** [comment] 2017-11-03 04:41
kk, I'm going to take a look at this, since @whyrusleeping pinged me over IRC to check it out.

**Comment by VictorBjelkholm** [comment] 2017-11-03 05:04
Sorry, had some modifications to add source-maps in production builds that apparently broke the styling... Fix is here: https://github.com/ipfs/webui/pull/604

**Comment by VictorBjelkholm** [comment] 2017-11-03 05:08
After getting webui to load the styles, I found a couple of other problems. I'll leave them here for now and create separate issues. 1) creating a directory hierarchy where the directory name has another directory inside it with the same name, the path in the top of "Files" tab only shows one level. 2) drag and drop files doesn't seem to work in Firefox.

**Comment by dryajov** [comment] 2017-11-03 05:23
ah, yup - can confirm those, was able to repro.

**Comment by hacdias** [comment] 2017-11-13 08:31
Hey @VictorBjelkholm, I can't reproduce the drag and drop issue on Firefox. Which version of FF are you using?

**Comment by diasdavid** [comment] 2017-11-17 22:08
Yeah, drag and drop is also working for me in Firefox quantum with https://github.com/ipfs/webui/pull/605, let's close this one

**Closed by diasdavid** 2017-11-17 22:08 UTC
Labels: bug
